on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Run your project's build step
      # - name: Build
      #   run: npm install && npm run build
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: hps4pc5aSyVPrbpYAWFLW3YacqycTcEUyypUXgRn
          accountId: 2226f40c3e3cec805a47b5a2e01c5b5f
          projectName: MLM3000# e.g. 'my-project'
          directory:  antflix/MaterialListGenerator # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
